Feature/improve api urlpatterns
scandamus/ft_transcendence pull request #200
Opened 2024-07-09 06:43 UTC by hachi868

2024-07-12 15:53 UTC, monksoffunk requested changes
WebSocketについてチェックしたところurls.pyでの指定は不要でした🙏

2024-07-12 15:53 UTC, monksoffunk commented on backend/scandamus/players/urls/players.py
> +    path('recommend/', RecommendedView.as_view(), name='recommend'),
```suggestion
    path('recommend/', RecommendedView.as_view(), name='recommend'),
    path('level/', UserLevelView.as_view(), name='user_level'),
```

2024-07-12 15:53 UTC, monksoffunk commented on backend/scandamus/players/urls/players.py
> +from ..views import LoginView, UserInfoView, LogoutView, RegisterView, DeleteUserView, ValidateView, AvatarUploadView, MatchLogView, RecommendedView
```suggestion
from ..views import LoginView, UserInfoView, LogoutView, RegisterView, DeleteUserView, ValidateView, AvatarUploadView, MatchLogView, RecommendedView, UserLevelView

```

2024-07-12 15:53 UTC, monksoffunk commented on backend/scandamus/players/urls/players.py
> +    path('recommend/', RecommendedView.as_view(), name='recommend'),
先にマージされたlevelが反映されないですね（これは仕方ないGitHubの罠）

2024-07-12 15:53 UTC, monksoffunk commented on backend/scandamus/game/urls/lounge.py
game/urls/lounge.pyはまるごと不要でした

2024-07-12 15:53 UTC, monksoffunk commented on backend/scandamus/scandamus/urls.py
> +    path('ws/lounge/', include('game.urls.lounge')),
```suggestion
```
WebSocketについては削除でOKです

2024-07-12 16:42 UTC, hachi868 commented
> WebSocketについてチェックしたところurls.pyでの指定は不要でした🙏

ありがとうございます！suggestion承認しました🙏

2024-07-13 03:28 UTC, monksoffunk requested changes
api/players経由でもdelete出来てしまう構造でした
追加で修正をおねがいいたしたく🙏

2024-07-13 03:28 UTC, monksoffunk commented on backend/scandamus/scandamus/urls.py
> +    path('api/test/', include('players.urls.players')), # for test use only
```suggestion
    path('api/test/', include('players.urls.test')), # for test use only
```
すいません！　追加でこちらを別ルールに分けないとでした
現状のplayers/urls/players.pyをコピーしてplayers/urls/test.pyとしておくと良さそうです

2024-07-13 03:28 UTC, monksoffunk commented on backend/scandamus/players/urls/players.py
> +    path('delete/<str:username>/', DeleteUserView.as_view(), name='delete_user'),
```suggestion
```
players.pyをまるごとtest.pyにコピした後で
players.pyから上記の行を削除いただければと🙏

2024-07-15 15:17 UTC, hachi868 commented
> api/players経由でもdelete出来てしまう構造でした 追加で修正をおねがいいたしたく🙏

コメントしそびれてましたが、こちら対応しました。
お手隙でお願いします🙏

2024-07-15 23:43 UTC, monksoffunk approved these changes
ありがとうございました！

2024-07-16 08:22 UTC, Chanmachan approved these changes

2024-07-19 11:22 UTC, snara-42 approved these changes

2024-07-26 12:12 UTC, merged