Feature/change score and state when player exit
scandamus/ft_transcendence pull request #212
Opened 2024-07-12 17:09 UTC by Chanmachan

## 実装した機能
- dual,quadでexitボタンを押した時の処理を追加しました
- duql: 片方がexitした時点でゲームが終わります
- quad: exitした人のみ-1になりpaddleが壁になります。残り一人になるまでゲームは続きます

## その他
- 面倒ごと増やす気はあまりないですが、いざ実装してみるとexitしたときに急にゲーム終わるのは相手からしてみると「!?」って感じで不親切な感じもしますね。後でスコア-1を確認すれば、切断には気づけると思いますが。

2024-07-13 05:44 UTC, monksoffunk commented
試合終了後に得点と勝敗結果を表示する画面（モーダルか）を作った方がユーザーフレンドリーですね
別途考えましょう（誰か氏…）

2024-07-13 05:48 UTC, monksoffunk reviewed
player1側が退出してもマッチが終わらない？

2024-07-13 05:52 UTC, Chanmachan commented
> player1側が退出してもマッチが終わらない？

確認します

2024-07-13 10:03 UTC, hachi868 commented
試合終了 => DB格納 => socketで処理終了を受け取って結果をフロント表示 => 数秒後ページ移動
のようなフローを踏むと、Dashboardに表示する内容が古いままみたいな事故も防げて良さそうです。
現時点の挙動の感じだと、結果表示までのもたつきも感じさせずに済みそうですし

2024-07-15 14:35 UTC, Chanmachan commented
> 試合終了 => DB格納 => socketで処理終了を受け取って結果をフロント表示 => 数秒後ページ移動 のようなフローを踏むと、Dashboardに表示する内容が古いままみたいな事故も防げて良さそうです。 現時点の挙動の感じだと、結果表示までのもたつきも感じさせずに済みそうですし

数秒後ページ移動はsetTimeoutを使って遅らせる形で良さそうですかね？

2024-07-15 19:53 UTC, Chanmachan commented
> > 数秒後ページ移動はsetTimeoutを使って遅らせる形で良さそうですかね？
> 
> 良いと思います！3秒くらいでしょうか （表示内容の確認には十分、且つ待たされ感の出てくる前に移動したい） 結果表示まわり、ざっくりで置いておいていただければ拾います🙏

setTimeoutを使ったものをpushしました。
canvas内で勝ち負けを表示してみたりしてたのですが、今はコメントアウトしてます(ダサかった)。
timeout処理いれた場合、exitボタン押した後に一瞬で遷移せずに待機することになりますが、modal閉じて待機かそのままでいいのか、それとも他の道があるのかで悩んでて現在はmodal開いたまま待機することになってます。quadはゲーム人数が足りてる限りexitしてもすぐ遷移しますが。ここら辺まだしっくりきたものが作れてません；；

2024-07-16 02:37 UTC, monksoffunk requested changes

2024-07-16 02:37 UTC, monksoffunk commented on frontend/static_vol/js/components/GamePlay.js
> +                    }, 3000);
3秒待ってからwsをcloseするとトーナメントでの次のゲーム開始が先行してしまう
closeしてから遷移のみsetTimeoutにすればいいかと思いましたが、今度はdestroyが発生するのが3秒後になって保持していたall_usernamesがリムーブされてしまってエラー（当然ゲーム画面が出ない）

2024-07-31 17:05 UTC, closed without merging