Feature/add tournament waiting room
scandamus/ft_transcendence pull request #220
Opened 2024-07-16 21:21 UTC by hachi868

2024-07-21 01:51 UTC, monksoffunk requested changes
レイアウトばっちりでしたね

2024-07-21 01:51 UTC, monksoffunk commented on frontend/static_vol/js/components/TournamentDetail.js
> +        if (match.score1) {
```suggestion
        if (match.score1 !== undefined && match.score1 !== null) {
```
0点のときに「？」が表示されてしまうようです

2024-07-21 01:51 UTC, monksoffunk commented on frontend/static_vol/js/components/TournamentDetail.js
> +        if (match.score2) {
```suggestion
        if (match.score2 !== undefined && match.score2 !== null) {

```

2024-07-21 08:16 UTC, hachi868 commented
> 0点のときに「？」が表示されてしまうようです
失礼しました。。suggestありがとうございます！

2024-07-21 14:25 UTC, monksoffunk approved these changes
OKです！

2024-07-26 10:13 UTC, snara-42 approved these changes
待合室にメッセージが表示されることを確認しました

2024-07-26 12:19 UTC, Chanmachan approved these changes

2024-07-26 12:57 UTC, merged