Feature/limit save fields
scandamus/ft_transcendence pull request #280
Opened 2024-07-29 17:20 UTC by hachi868

2024-07-30 22:26 UTC, hachi868 commented on backend/scandamus/game/tournament_match.py
>          create_match(tournament, first_match.winner, second_match.winner, -6)
関数内外で複数回`tournament.save()`しているようです

2024-07-30 22:28 UTC, hachi868 commented on backend/scandamus/game/tournament_match.py
>          notify_players(tournament.name, [tournament.third_place.id], 'notifyFinalOnGoing', False)#3位には決勝戦進行中表示
関数内外で複数回`tournament.save()`している

2024-07-30 22:56 UTC, hachi868 commented
これはラウンジmatchの終了した際のログなのですが
player, Match, それぞれ複数回保存が走っているようです

```
//player save() testplayer11
//-- Player save() on: set_players_to_waiting
//player save() testplayer13
//-- Player save() on: set_players_to_waiting

//Match save() pong
//-- Match save() on: update
//-- serializer.save() on: MatchViewSet perform_update

//Match save() pong
//-- Match save() on: set_winner

//player save() testplayer11
//-- Player save() on: set_all_players_status
//player save() testplayer13
//-- Player save() on: set_all_players_status
```

1つ目の`player save()`は`MatchSerializer`の`update`、`set_players_to_waiting`由来
2つ目の`player save()`は`MatchViewSet`の`update`、`set_all_players_status`由来

2024-07-31 11:16 UTC, monksoffunk requested changes
現状、トーナメントが動かないようです
修正案を入れた部分を反映してもマッチはプレイできるようになるものの、試合結果を正常に更新できないらしく、全員負けになります。

自分が書いたMatchでviewsとserializerで重複したコードがややこしく、いずれにしても #281 （update_fieldsを指定してます）で変更になるため、可能であれば #281を先にマージした方が楽な気がします。

2024-07-31 11:16 UTC, monksoffunk commented on backend/scandamus/game/tournament_match.py
> -        match.save()
tournament.matches.add(match)で指定するmatchはデータベース上に必要なため、
match.save()はここに必要（Matchで生成したオブジェクトはメモリ上のみに存在）

2024-07-31 11:16 UTC, monksoffunk commented on backend/scandamus/game/tournament_match.py
> +        tournament.save(update_fields=['bye_player', 'matches'])
```suggestion
        tournament.save(update_fields=['bye_player'])
```
manytomanyのフィールドはupdate_fieldsに指定できない仕様
addで追加しているので問題ないようです

2024-07-31 11:28 UTC, hachi868 commented
> 現状、トーナメントが動かないようです 修正案を入れた部分を反映してもマッチはプレイできるようになるものの、試合結果を正常に更新できないらしく、全員負けになります。
> 
> 自分が書いたMatchでviewsとserializerで重複したコードがややこしく、いずれにしても #281 （update_fieldsを指定してます）で変更になるため、可能であれば #281を先にマージした方が楽な気がします。

ありがとうございます！失礼しました
他PR待ち＆動作確認したいので一旦Draftにします

2024-08-01 17:47 UTC, hachi868 commented on backend/scandamus/game/tournament_match.py
> +        tournament.save(update_fields=['bye_player', 'matches'])
ありがとうございます🙏こちらmergeしました

2024-08-01 17:58 UTC, hachi868 commented
諸々修正しまして、トーナメント動くようになりました。
こちらでご確認お願いします！

2024-08-06 05:18 UTC, Chanmachan commented
ログをみながらトーナメント含め正常に動作しているのを確認しました

2024-08-06 05:19 UTC, Chanmachan approved these changes

2024-08-06 05:52 UTC, merged