base作成
scandamus/ft_transcendence pull request #3
Opened 2024-05-05 08:46 UTC by hachi868

Base調整しました。
ご確認お願いします！

`docker-compose up --build -d`で起動できるかと。
`.env`はdiscordの機密情報チャンネルに貼りました。

テストユーザーが2人作成されて、`https://localhost:443` のフォームからログインできるはずです

2024-05-05 09:01 UTC, hachi868 commented on frontend/static_vol/js/components/Home.js
> +    }
クリックなどaddEventListenerでの挙動を登録する場合、
AfterRenderにはEventListener登録して
実際の挙動内容はまた別のメソッドに分ける形にしました。（とりあえずログインボタンの挙動について）

view移動時にremoveEventListenerしたいので、
addEventListenerしたらremove対象リストに追加お願いします。↓この形式で。
`this.addListenEvent(btnLogin, this.handleLogin, "click");`

2024-05-06 03:14 UTC, snara-42 requested changes
`s/resist/regist/g`

2024-05-06 03:44 UTC, monksoffunk approved these changes
ログインまで確認しました

2024-05-06 04:02 UTC, Chanmachan approved these changes
login successfulまで問題なく動きました

2024-05-06 04:18 UTC, snara-42 approved these changes
login successful できました

2024-05-06 05:40 UTC, merged