42login
scandamus/ft_transcendence pull request #314
Opened 2024-08-06 05:09 UTC by hachi868

- Homeの「42LOGIN」ボタンからログイン
- login名が他playerと重複する場合、42を付与。それでも重複すればa-z0-9からランダムに文字付与
- avatarはintra設定の写真を取得

2024-08-06 07:41 UTC, hachi868 commented
- [ ] `socialaccount`系のtableに関してmigrationが走らない
- [ ] friend申請

2024-08-07 03:27 UTC, monksoffunk commented
起動時にエラーが出てしまいます

実行手順
- 新規にclone
- データベースなし
- up --build

```
backend       | Traceback (most recent call last):
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
backend       |     return self.cursor.execute(sql, params)
backend       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend       | psycopg2.errors.UndefinedTable: relation "auth_user" does not exist
backend       | LINE 1: SELECT 1 AS "a" FROM "auth_user" WHERE ("auth_user"."is_supe...
backend       |                              ^
backend       | 
backend       | 
backend       | The above exception was the direct cause of the following exception:
backend       | 
backend       | Traceback (most recent call last):
backend       |   File "/app/manage.py", line 22, in <module>
backend       |     main()
backend       |   File "/app/manage.py", line 18, in main
backend       |     execute_from_command_line(sys.argv)
backend       |   File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
backend       |     utility.execute()
backend       |   File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
backend       |     self.fetch_command(subcommand).run_from_argv(self.argv)
backend       |   File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 412, in run_from_argv
backend       |     self.execute(*args, **cmd_options)
backend       |   File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 458, in execute
backend       |     output = self.handle(*args, **options)
backend       |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend       |   File "/usr/local/lib/python3.12/site-packages/django/core/management/commands/shell.py", line 127, in handle
backend       |     exec(sys.stdin.read(), globals())
backend       |   File "<string>", line 4, in <module>
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1241, in exists
backend       |     return self.query.has_results(using=self.db)
backend       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 566, in has_results
backend       |     return compiler.has_results()
backend       |            ^^^^^^^^^^^^^^^^^^^^^^
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1528, in has_results
backend       |     return bool(self.execute_sql(SINGLE))
backend       |                 ^^^^^^^^^^^^^^^^^^^^^^^^
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1560, in execute_sql
backend       |     cursor.execute(sql, params)
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 102, in execute
backend       |     return super().execute(sql, params)
backend       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 67, in execute
backend       |     return self._execute_with_wrappers(
backend       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
backend       |     return executor(sql, params, many, context)
backend       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 84, in _execute
backend       |     with self.db.wrap_database_errors:
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
backend       |     raise dj_exc_value.with_traceback(traceback) from exc_value
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
backend       |     return self.cursor.execute(sql, params)
backend       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend       | django.db.utils.ProgrammingError: relation "auth_user" does not exist
backend       | LINE 1: SELECT 1 AS "a" FROM "auth_user" WHERE ("auth_user"."is_supe...
backend       |                              ^
backend       | 
celery        | [2024-08-07 03:26:01,504: INFO/MainProcess] mingle: all alone
celery        | [2024-08-07 03:26:01,514: INFO/MainProcess] celery@d3d895623556 ready.
db            | 2024-08-07 03:26:01.598 UTC [82] ERROR:  relation "auth_user" does not exist at character 22
db            | 2024-08-07 03:26:01.598 UTC [82] STATEMENT:  SELECT 1 AS "a" FROM "auth_user" WHERE ("auth_user"."is_superuser" AND "auth_user"."username" = 'userSuper') LIMIT 1
backend       | Traceback (most recent call last):
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
backend       |     return self.cursor.execute(sql, params)
backend       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend       | psycopg2.errors.UndefinedTable: relation "auth_user" does not exist
backend       | LINE 1: SELECT 1 AS "a" FROM "auth_user" WHERE ("auth_user"."is_supe...
backend       |                              ^
backend       | 
backend       | 
backend       | The above exception was the direct cause of the following exception:
backend       | 
backend       | Traceback (most recent call last):
backend       |   File "/app/manage.py", line 22, in <module>
backend       |     main()
backend       |   File "/app/manage.py", line 18, in main
backend       |     execute_from_command_line(sys.argv)
backend       |   File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
backend       |     utility.execute()
backend       |   File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
backend       |     self.fetch_command(subcommand).run_from_argv(self.argv)
backend       |   File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 412, in run_from_argv
backend       |     self.execute(*args, **cmd_options)
backend       |   File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 458, in execute
backend       |     output = self.handle(*args, **options)
backend       |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend       |   File "/usr/local/lib/python3.12/site-packages/django/core/management/commands/shell.py", line 127, in handle
backend       |     exec(sys.stdin.read(), globals())
backend       |   File "<string>", line 5, in <module>
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1241, in exists
backend       |     return self.query.has_results(using=self.db)
backend       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 566, in has_results
backend       |     return compiler.has_results()
backend       |            ^^^^^^^^^^^^^^^^^^^^^^
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1528, in has_results
backend       |     return bool(self.execute_sql(SINGLE))
backend       |                 ^^^^^^^^^^^^^^^^^^^^^^^^
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1560, in execute_sql
backend       |     cursor.execute(sql, params)
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 102, in execute
backend       |     return super().execute(sql, params)
backend       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend       |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 67, in execute
backend  [...]

2024-08-07 05:21 UTC, hachi868 commented
> 起動時にエラーが出てしまいます

すみません！migration でした。。
これを機にmigrationファイルまとめました。
再度ですみませんがご確認お願いします

2024-08-07 07:02 UTC, monksoffunk requested changes
ありがとうございます
- 起動するようになりました
- 自分の42アカウントでログイン出来ました
- 別のウィンドウから同じ42アカウントで同時ログイン出来てしまいます…多重ログイン防止のためにPlayersのLoginViewと同じことをする必要があります

2024-08-07 11:39 UTC, hachi868 commented on backend/scandamus/providers42/views.py
> +    raise Exception("NoUsernamesAvailable")
ありがとうございます！
ランダムに文字列追加するようにしました。
ご確認お願いします

2024-08-07 11:40 UTC, hachi868 commented
> 別のウィンドウから同じ42アカウントで同時ログイン出来てしまいます…多重ログイン防止のためにPlayersのLoginViewと同じことをする必要があります

失礼しました、同時ログイン弾くようにしました。

2024-08-07 12:19 UTC, monksoffunk approved these changes
確認しました！

2024-08-07 12:57 UTC, Chanmachan approved these changes
すごいです！末尾に42,ランダム文字がつく、別タブログインできるのを確認できました

2024-08-07 13:01 UTC, merged